### ISSUE TITLE
Incorrect terminology

### ISSUE THREAD

**Issue by JimMoyle** [microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise#10]
Abstract and learning objectives

WVD is the service name, we don't publish windows virtual desktops, we just publish desktops and apps.

**Comment by JimMoyle** [comment]
Created PR 
https://github.com/microsoft/MCW-Implementing-Windows-Virtual-Desktop-in-the-enterprise/pull/11

**Comment by DawnmarieDesJardins** [comment]
@JimMoyle
Hi Jim, thanks for the review!  I've mentioned your issues inside the update PR for the author's to review.  No need to create a PR, they'll update their PR with all SME review comments.  To help the authors keep track, please add any additional feedback at the bottom of the FY2021 Q4 update PR.  We appreciate your help!

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #9 - thanks Jim!
