### ISSUE TITLE
Shouldn't use master/slave terminology

### ISSUE THREAD

**Issue by JimMoyle** [microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise#12]
Throughout the doc 'master' image is used.  As gold image is used within the industry interchangeably with master image and doesn't have the same negative connotations so we should use gold instead of master.

**Comment by JimMoyle** [comment]
https://github.com/microsoft/MCW-Implementing-Windows-Virtual-Desktop-in-the-enterprise/pull/13

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #9
