### ISSUE TITLE
Issues with Lab Guide

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise#14]
In Exercise- 3> Task- 3> Step 20, I was not able to find the Active Directory Domain Services enabled option.

![image](https://user-images.githubusercontent.com/81952290/129255955-2d04abf1-2501-41c9-bb9b-8345c88f21d2.png)

In Exercise- 4> Task- 5> Step- 6, The UI to create an image has changed.

![image](https://user-images.githubusercontent.com/81952290/129226862-c12b130a-d123-48ee-80c7-ea63250c1d17.png)

![image](https://user-images.githubusercontent.com/81952290/129226884-353a1b8f-21c2-48f7-b27d-edfe28c0659b.png)

**Comment by dwnatwick** [comment]
Images have been adjusted on pull request

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #15. Thanks all!
