### ISSUE TITLE
Lab Guide UI and functional Updates

### ISSUE THREAD

**Issue by Kalyani7744** [microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise#17]
1. [Exercise 1, Task 3, Step 3](https://github.com/microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Implementing%20Azure%20Virtual%20Desktop%20in%20the%20enterprise.md#task-3-creating-a-domain-admin-account): After entering Password, the instruction for enabling “user must change password at next logon” is not given. Instruction has to be updated.

2. [Exercise 4, task 5, step 6](https://github.com/microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Implementing%20Azure%20Virtual%20Desktop%20in%20the%20enterprise.md#task-5-create-a-managed-image-from-the-gold-image-vm): For creating VM Image, details are not given properly in instruction. When I followed the details in screenshot and tried to create image, the Image was not created as shown in lab guide. The UI for creating Image has changed as shown below.

![image](https://user-images.githubusercontent.com/83349665/129907578-3bcab1de-78d9-4bd5-a45c-f7082970a9a0.png)

![image](https://user-images.githubusercontent.com/83349665/129907631-a16dd8e3-2e43-49b4-aac2-29b94da717ee.png)

3. [Exercise 5, task 1](https://github.com/microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Implementing%20Azure%20Virtual%20Desktop%20in%20the%20enterprise.md#task-6-provision-a-host-pool-with-a-custom-image) & [Exercise 6, task 1](https://github.com/microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Implementing%20Azure%20Virtual%20Desktop%20in%20the%20enterprise.md#task-6-provision-a-host-pool-with-a-custom-image): There is an UI update for creating the hostpool which ask for “Domain to join” details as shown in the below image and those details are not updated in the lab guide. 

   Instructions and screenshot has to be updated.

![image](https://user-images.githubusercontent.com/83349665/129908417-71cd3d0b-785c-44c4-80f2-1b0e5178b683.png)

![image](https://user-images.githubusercontent.com/83349665/129908479-82a19888-6c69-41a6-84b9-7ade2f3e51de.png)

4.  [Exercise 5, task 1](https://github.com/microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Implementing%20Azure%20Virtual%20Desktop%20in%20the%20enterprise.md#task-6-provision-a-host-pool-with-a-custom-image) & [Exercise 6, task 1](https://github.com/microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Implementing%20Azure%20Virtual%20Desktop%20in%20the%20enterprise.md#task-6-provision-a-host-pool-with-a-custom-image): The use need to select **Validation environment** inside **Basics** tab as yes. It is not mentioned in the lab guide and giving it as no will result in unavailability of **session hosts**

![image](https://user-images.githubusercontent.com/83349665/129909475-ae0cfa53-70cc-40bb-9717-576ef7698244.png)

**Comment by DawnmarieDesJardins** [comment]
@Kalyani7744 
Thank you for bringing this to our attention!  It looks like there's been recent changes to AVD so we're going to have our authors test/fix the entire workshop to make sure everything is correct.  Please look for updated content before the end of the month.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #18
