### ISSUE TITLE
issues found while performing the lab

### ISSUE THREAD

**Issue by Eddevinc** [microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise#19]
1. Exercise 4: Create a golden image for AVD, Task 3: prepare AVD Image, step 10 where Microsoft Teams and Edge is not getting installed.

2. Exercise 3, task 3, step 8: The zip file is extracted in AzFilesHybrid\AzFilesHybrid hence the command should be

 "cd C:\Users\ADAdmin\Documents\AzFilesHybrid\AzFilesHybrid" instead of "cd C:\Users\ADAdmin\Documents\AzFilesHybrid\AzFilesHybrid"

**Comment by dwnatwick** [comment]
@Eddevinc.  The note states to update these settings as necessary.  So, if you would like to install MS Teams and Edge, you are welcome to make this customization yourself.  I believe that the reason for this is to decrease the amount of time for additional installations.  I adjusted the file name path per your recommendation.  Thank you.
