### ISSUE TITLE
Facing issues  in understanding few steps and there are few content/ screenshot updates.

### ISSUE THREAD

**Issue by Eddevinc** [microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise#22]
1. We have added new "avdadmin" user and added to DomainAdmin group in E1>T3. We have a note to use it for Hostpool Domain Join but it is better to mention the note while creating Hostpools at in Ex5>T1>S5 & Ex6>T1>S6

2. In E2>T1 we are adding 7 Users to groups(AVD Pooled Desktop User | AVD Remote App All Users | AVD Persistent Desktop User). In Ex5>T3>S6 we have added AVD Pooled Desktop User on Market Place Image App Group and in Ex6>T3>S9 added AVD Remote App All Users + AAD DC Admin to Custom Image App Group but in Ex7>T1>S2 better to mention clearly which account need to be used. If user's which is part of 7 created users, need to clearly mention on obtaining user password.

3.  In Ex4>T3>S8: Script failing to bring up the UI to install Apps.

4. While creating both Hostpools it is not clear which Vnet to be selected.

5. In Ex4>T6 it is mentioned to refer Ex6 for Hostpool creation. It is creating confusion, we don't require this as it is clearly instructed in Ex6. (Hence we end up performing exercise 6 two times)

6. In Ex6>T3>S5: Placed wrong screenshot.

7. Was not able to get Desktop Client App due to issue faced in preparing image using script.

**Comment by dwnatwick** [comment]
We will take a look at this.  Can you please provide details on where #4 and #7 issues are located.  Thank you very much.

**Comment by Eddevinc** [comment]
#4 is at exercise 5 and 6

#7 is at Exercise 4, task 3, step 8

**Comment by KitSkin** [comment]
@Eddevinc on 7. in Exercise 4, task 3, step 8, please ensure that you are running the script in a PowerShell command line window (powershell.exe) and **_not_** running the Integrated Scripting Environment (ISE) version (powershell_ise.exe).  This will also work with PowerShell Core (pwsh.exe), but the Client App shows the form on multiple iterations I've attempted.  If you're continuing to have issues with `.\Prepare-WVDImage.ps1 -DisplayForm` within powershell.exe, please let us know.

**Comment by DawnmarieDesJardins** [comment]
Reassigned issue to texnomore for visibility and KitSkin for the fix.

**Comment by KitSkin** [comment]
> 4. While creating both Hostpools it is not clear which Vnet to be selected.
@Eddevinc the screenshots are intended to include all the settings to be used for the deployments including the VNet names.  Those in the image should be the ones used.

**Comment by texnomore** [comment]
All issues on this should now be addressed. Closing out; however, if there are any other issues please let me know! Thank you!
