### ISSUE TITLE
2021 Q4 proposed updates

### ISSUE THREAD

**Issue by dwnatwick** [microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise#5]
MCW WVD WDS Update proposals
•	Screen capture protection (public preview) - prevent data being exfiltrated by clients using screen captures
•	Start virtual machine on connect (public preview) - Built-in functionality useful for personal desktops to allow VMs to be shutdown and start up when a user logs in to save on compute costs
•	RDP Shortpath (preview) - connect to backend over private network for lower latency after authenticating via public portal
•	RBAC Roles for WVD - Integrate in RBAC Desktop Virtualization * roles for management team roles
•	MSIX App Attach via Azure Portal - allow applications to be centrally managed and stored without having to regularly update hosts and can now be managed via the portal and start menu settings.
•	Ensure specifically calling out WVD integrations of Azure Security baseline, Monitor, and Defender Endpoint

MCW WVD HOL Update proposals
•	Configure Azure Automation to autoscale pooled pool
o	Deploy automation and Logic App
o	Login to pool and use app to artificially use CPU load
•	RBAC Roles for WVD
o	Add management accounts to Desktop Virtualization RBAC rules
•	MSIX App Attach via Azure Portal - allow applications to be centrally managed and stored without having to regularly update hosts and can now be managed via the portal and start menu settings.
o	Create basic MSIX app from MSI using packaging tool
o	Convert MSIX app to MSIX image (VHD) using MSIXMGR
o	Store MSIX VHD on Files Share
o	Configure Host VMs to use MSIX
o	Add MSIX app to start menu
o	Login and validate app works
•	Azure Security baseline, Monitor, and Defender Endpoint for WVD integration
•	Rolling update of pool using Image Gallery
o	Import disk directly into an image gallery
o	Deploy from image gallery (instead of directly from managed image)
o	Log user(s) into initial image
o	Create VM from image and update (additional tool)
o	Sysprep VM and add as new version to gallery
o	Add new host to host pool (uses new image automatically)
o	Set old host to drain logins
o	Log out and log in with account to see new app
o	Kick out user from old host
o	Delete old hosts

Before the HOL updates?
•	Image as BtHOL? – remove image building time from actual WVD lab for sake of time
o	Have them do the initial Image and Image Gallery prior to the HOL and move it to the Before the HOL
- or –
o	Include Shared Image Gallery in template and copy over a base image as part of template
•	Either of them could allow the student to not have to spend more time in the lab focusing on WVD but still do the syspreping for the rolling update change above.

**Comment by DawnmarieDesJardins** [comment]
Closing as complete with merge of PR #9
