### ISSUE TITLE
Could not connect to resources. 

### ISSUE THREAD

**Issue by LucaOtto** [microsoft/MCW-Implementing-Azure-Virtual-Desktop-in-the-enterprise#8]
I configured all the resources and when I go to https://rdweb.wvd.microsoft.com/arm/webclient/index.html I can see the list of apps and a personal desktop listed 
![image](https://user-images.githubusercontent.com/42404744/118789845-18bef780-b88d-11eb-9cd0-103893704050.png)

However when trying to launch any of them I receive this error:
![image](https://user-images.githubusercontent.com/42404744/118789962-355b2f80-b88d-11eb-8025-6071aa4e8357.png)

The VMs are running and objects in AD are also created.
![image](https://user-images.githubusercontent.com/42404744/118790137-65a2ce00-b88d-11eb-940d-6488b1052c26.png)

Can you please advise? Error doesn't provide any clues.

Thanks

**Comment by dwnatwick** [comment]
@LucaOtto.  Is the user licensed for Microsoft 365 applications?  Have you attempted a connection to the Remote Desktop rather than just the apps?  Thank you very much.

**Comment by LucaOtto** [comment]
@dwnatwick : yes I attempted to connect to the desktops ( pooled and single). Same error. The users are demo users generated through the M365 portal. It shows that users are synched via AD Connect to the local AD ( Exercises 1 to 4).

**Comment by dwnatwick** [comment]
@LucaOtto . Did you assign the O365 licenses to the users when they were created?

**Comment by KitSkin** [comment]
@LucaOtto, if you go to the WVD Host Pool, under the **Overview** section, is the Unavailable listed as '**0**'?  Another way to look at it, if you look at your Session Hosts for your host pool do they both have an '**Available**' status and Drain Mode '**Off**'?
![image](https://user-images.githubusercontent.com/42873266/118865734-e02c1780-b8a6-11eb-8c95-77a5f44b62f6.png)

**Comment by KitSkin** [comment]
Also, if you've been sitting idle on the website for 30 minutes or more, your [token](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes) could have expired as well.  To resolve this, just sign out the session and sign back in.

**Comment by LucaOtto** [comment]
@KitSkin yes, they are available and drain mode off. I connected to the desktop and/or published apps within a minute of completing the backend system setup, I don't believe it's because of the above.

**Comment by KitSkin** [comment]
Could you enable [diagnostics and Log Analytics](https://docs.microsoft.com/en-us/azure/virtual-desktop/diagnostics-log-analytics) to help centralize the error reporting for diagnostics?

**Comment by KitSkin** [comment]
the Log Analytics make it easier to diagnose the problem by putting everything in one place to query against, but you can also go to each resource and use the troubleshooting guides to examine errors on each:
https://docs.microsoft.com/en-us/azure/virtual-desktop/troubleshoot-vm-configuration

One thing you might want to do is try with the [Remote Desktop Client](https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-windows-7-10) rather than the web client. Sometimes the errors will be logged with more verbosity in your local Event Log that aren't necessarily translated through the web client without the diagnostic logs enabled.

**Comment by DawnmarieDesJardins** [comment]
Closing issue - no additional communication from field & recent update merge with PR #9
